version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend
    restart: always
    volumes:
      - ./:/src
    ports:
      - "8081:8081"
    environment:
      - TZ=Africa/Tunis